# Generated by Django 5.1.2 on 2024-10-29 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('total_time', models.IntegerField()),
                ('yields', models.IntegerField()),
                ('instructions', models.TextField()),
                ('image', models.URLField(blank=True, max_length=500, null=True)),
                ('ingredient_groups', models.TextField(blank=True, null=True)),
                ('instructions_list', models.TextField(blank=True, null=True)),
                ('equipment', models.TextField(blank=True, null=True)),
                ('keywords', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'recipes',
                'managed': False,
            },
        ),
    ]
