# Generated by Django 5.1.2 on 2024-11-14 07:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0002_ingredient_alter_recipe_options_recipeingredient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='recipeingredient',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_ingredient_table', to='hello.recipe'),
        ),
        migrations.AlterModelTable(
            name='recipe',
            table='recipe_table',
        ),
    ]
